### ISSUE TITLE
27% timmed mean mis-calculation

### ISSUE THREAD

**Issue by WaleedMortaja** [mdozmorov/BIOS567.2017#2]
I think the 27% trimmed mean in [Trimmed_mean.pdf](https://github.com/mdozmorov/BIOS567.2017/blob/gh-pages/presentations/03_Image/Trimmed_mean.pdf) has a mis-calculation. I think we should throw 0.7 of the observation and keep 0.3 of it. The formula will then be
27% trimmed mean = (1 / 4.6) * ((_**0.3** *_ 6) + 7 + 11 + 21 + 81 + (_**0.3**_ * 90))

**Comment by mdozmorov** [comment]
Thank you, @WaleedMortaja, for noticing this. You are correct, and this has now been corrected in the PDF.
